"""empty message

Revision ID: 67064606c0bf
Revises: b75eebbb2d5e
Create Date: 2020-09-07 11:29:12.804775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67064606c0bf'
down_revision = 'b75eebbb2d5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('address', sa.String(), nullable=True))
    op.add_column('location', sa.Column('maps_id', sa.String(), nullable=True))
    op.add_column('location', sa.Column('name', sa.String(), nullable=True))
    op.create_index(op.f('ix_location_address'), 'location', ['address'], unique=False)
    op.create_index(op.f('ix_location_maps_id'), 'location', ['maps_id'], unique=False)
    op.create_index(op.f('ix_location_name'), 'location', ['name'], unique=False)
    op.add_column('masterclass', sa.Column('is_remote', sa.Boolean(), nullable=True))
    op.add_column('masterclass', sa.Column('remote_joining_instructions', sa.String(), nullable=True))
    op.add_column('masterclass', sa.Column('remote_url', sa.String(), nullable=True))
    op.create_index(op.f('ix_masterclass_is_remote'), 'masterclass', ['is_remote'], unique=False)
    op.create_index(op.f('ix_masterclass_remote_joining_instructions'), 'masterclass', ['remote_joining_instructions'], unique=False)
    op.create_index(op.f('ix_masterclass_remote_url'), 'masterclass', ['remote_url'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_masterclass_remote_url'), table_name='masterclass')
    op.drop_index(op.f('ix_masterclass_remote_joining_instructions'), table_name='masterclass')
    op.drop_index(op.f('ix_masterclass_is_remote'), table_name='masterclass')
    op.drop_column('masterclass', 'remote_url')
    op.drop_column('masterclass', 'remote_joining_instructions')
    op.drop_column('masterclass', 'is_remote')
    op.drop_index(op.f('ix_location_name'), table_name='location')
    op.drop_index(op.f('ix_location_maps_id'), table_name='location')
    op.drop_index(op.f('ix_location_address'), table_name='location')
    op.drop_column('location', 'name')
    op.drop_column('location', 'maps_id')
    op.drop_column('location', 'address')
    # ### end Alembic commands ###
