"""Add physical location details to masterclass

Revision ID: 86193db96139
Revises: 67064606c0bf
Create Date: 2020-11-09 20:42:14.108631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86193db96139'
down_revision = '67064606c0bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('masterclass', sa.Column('building_instructions', sa.String(), nullable=True))
    op.add_column('masterclass', sa.Column('floor', sa.String(), nullable=True))
    op.add_column('masterclass', sa.Column('room', sa.String(), nullable=True))
    op.create_index(op.f('ix_masterclass_building_instructions'), 'masterclass', ['building_instructions'], unique=False)
    op.create_index(op.f('ix_masterclass_floor'), 'masterclass', ['floor'], unique=False)
    op.create_index(op.f('ix_masterclass_room'), 'masterclass', ['room'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_masterclass_room'), table_name='masterclass')
    op.drop_index(op.f('ix_masterclass_floor'), table_name='masterclass')
    op.drop_index(op.f('ix_masterclass_building_instructions'), table_name='masterclass')
    op.drop_column('masterclass', 'room')
    op.drop_column('masterclass', 'floor')
    op.drop_column('masterclass', 'building_instructions')
    # ### end Alembic commands ###
