"""Add category column

Revision ID: bcd3cfe07b70
Revises: 0ebeb48ca191
Create Date: 2020-02-25 17:27:03.031001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcd3cfe07b70'
down_revision = '0ebeb48ca191'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('masterclass_content', sa.Column('category', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('masterclass_content', 'category')
    # ### end Alembic commands ###
